server:
  port: 8888
spring:
  application:
    name: config-server
  data:
    mongodb:
      uri: ${MONGODB_URI}
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/urosrelic/pmf-food-ordering-service


